# Generated by Django 4.0.3 on 2022-04-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Kategoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Maqola nomi')),
                ('content', models.TextField(blank=True, verbose_name='Maqola matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'yilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yagilangan vaqti')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasmi')),
                ('published', models.BooleanField(default=True, verbose_name="Qo'shish")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Kategoriya')),
            ],
        ),
    ]
